# Generated by Django 5.2.13 on 2026-04-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='propertyamenitymap',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyamenity'),
        ),
        migrations.AddField(
            model_name='propertyamenitymap',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyblackout',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='properties.property'),
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property'),
        ),
        migrations.AddField(
            model_name='roomamenitymap',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.roomamenity'),
        ),
        migrations.AddField(
            model_name='roomamenitymap',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.room'),
        ),
        migrations.AddField(
            model_name='roomblackout',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='properties.room'),
        ),
        migrations.AddField(
            model_name='roomrateplan',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='properties.room'),
        ),
        migrations.AddField(
            model_name='roomhourlyrate',
            name='rate_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='properties.roomrateplan'),
        ),
        migrations.AddField(
            model_name='roomdailyrate',
            name='rate_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='properties.roomrateplan'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['vendor'], name='properties_vendor__10d13c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'city'], name='properties_status_ab26d7_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured'], name='properties_feature_b7a303_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenitymap',
            unique_together={('property', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property'], name='rooms_propert_67d9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='rooms_status_ee4627_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomamenitymap',
            unique_together={('room', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='roomhourlyrate',
            unique_together={('rate_plan', 'duration_minutes')},
        ),
        migrations.AlterUniqueTogether(
            name='roomdailyrate',
            unique_together={('rate_plan', 'weekday')},
        ),
    ]
