# Generated by Django 5.1.15 on 2026-04-26 22:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_image_id", models.BigIntegerField(db_index=True, default=0)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("group_id", models.CharField(blank=True, max_length=80)),
                ("group", models.CharField(blank=True, max_length=120)),
                ("group_entity_id", models.IntegerField(blank=True, null=True)),
                ("provider_id", models.IntegerField(blank=True, null=True)),
                ("type_id", models.IntegerField(blank=True, null=True)),
                ("uploaded_date", models.DateTimeField(blank=True, null=True)),
                ("high_resolution_sizes", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_images",
            },
        ),
        migrations.CreateModel(
            name="HotelImageUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("size_key", models.CharField(max_length=40)),
                ("url", models.TextField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="properties.hotelimage",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_image_urls",
            },
        ),
        migrations.CreateModel(
            name="HotelLocationHighlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(blank=True, max_length=120)),
                ("tooltip", models.TextField(blank=True, null=True)),
                ("highlight_type", models.CharField(blank=True, max_length=80)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_highlights",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_location_highlights",
            },
        ),
        migrations.CreateModel(
            name="HotelNearbyPlaceCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_key", models.CharField(max_length=80)),
                ("category_name", models.CharField(max_length=120)),
                ("category_symbol", models.CharField(blank=True, max_length=120)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby_place_categories",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_nearby_place_categories",
            },
        ),
        migrations.CreateModel(
            name="HotelNearbyPlace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbr", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "duration_icon",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=18, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=18, null=True
                    ),
                ),
                ("landmark_id", models.IntegerField(blank=True, null=True)),
                ("type_id", models.IntegerField(blank=True, null=True)),
                ("type_name", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="properties.hotelnearbyplacecategory",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_nearby_places",
            },
        ),
        migrations.CreateModel(
            name="HotelPositiveMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facility_class_id", models.IntegerField()),
                ("name", models.CharField(max_length=120)),
                ("no_of_positive_mentioned", models.IntegerField(default=0)),
                ("facility_ids", models.JSONField(blank=True, default=list)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positive_mentions",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_positive_mentions",
            },
        ),
        migrations.CreateModel(
            name="HotelRecommendationScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequent_traveller_score",
                    models.IntegerField(blank=True, null=True),
                ),
                ("general_score", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_score",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_recommendation_scores",
            },
        ),
        migrations.CreateModel(
            name="HotelReviewScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_combined", models.BooleanField(default=False)),
                ("provider_id", models.IntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=10, max_digits=4),
                ),
                ("review_count", models.IntegerField(default=0)),
                (
                    "trending_past_14_days",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "trending_past_30_days",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_scores",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_review_scores",
            },
        ),
        migrations.CreateModel(
            name="HotelReviewGrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grade_id", models.CharField(max_length=60)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "city_average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "review_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="properties.hotelreviewscore",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_review_grades",
            },
        ),
        migrations.CreateModel(
            name="HotelReviewScoreDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tier_id", models.CharField(max_length=40)),
                ("review_count", models.IntegerField(default=0)),
                (
                    "review_score",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_distributions",
                        to="properties.hotelreviewscore",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_review_score_distributions",
            },
        ),
        migrations.CreateModel(
            name="HotelReviewSnippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snippet_id", models.CharField(blank=True, max_length=40)),
                ("country_code", models.CharField(blank=True, max_length=4)),
                ("country_name", models.CharField(blank=True, max_length=120)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("demographic_id", models.SmallIntegerField(blank=True, null=True)),
                ("demographic_name", models.CharField(blank=True, max_length=80)),
                ("reviewer", models.CharField(blank=True, max_length=120)),
                (
                    "review_rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("snippet", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_snippets",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_review_snippets",
            },
        ),
        migrations.CreateModel(
            name="HotelVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider_video_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("location", models.TextField()),
                (
                    "generated_type",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_videos",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_videos",
            },
        ),
        migrations.CreateModel(
            name="HotelAtfHighlight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(blank=True, max_length=120)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("topic_name", models.CharField(blank=True, max_length=120)),
                ("tooltip", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atf_highlights",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_atf_highlights",
                "indexes": [
                    models.Index(
                        fields=["property"], name="hotel_atf_h_propert_e0f0db_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HotelFavoriteFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_id", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=80)),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(blank=True, max_length=120)),
                ("tooltip", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_features",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_favorite_features",
                "indexes": [
                    models.Index(
                        fields=["property"], name="hotel_favor_propert_6be254_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="hotelimage",
            index=models.Index(
                fields=["property"], name="hotel_image_propert_7dcd2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotelimage",
            index=models.Index(
                fields=["group_id"], name="hotel_image_group_i_25aee5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hotelimageurl",
            unique_together={("image", "size_key")},
        ),
        migrations.AddIndex(
            model_name="hotellocationhighlight",
            index=models.Index(
                fields=["property"], name="hotel_locat_propert_caacdf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hotelnearbyplacecategory",
            unique_together={("property", "category_key")},
        ),
        migrations.AddIndex(
            model_name="hotelnearbyplace",
            index=models.Index(
                fields=["category"], name="hotel_nearb_categor_e5c16d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotelpositivemention",
            index=models.Index(
                fields=["property"], name="hotel_posit_propert_1a53b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hotelpositivemention",
            unique_together={("property", "facility_class_id")},
        ),
        migrations.AddIndex(
            model_name="hotelreviewscore",
            index=models.Index(
                fields=["property"], name="hotel_revie_propert_c32241_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hotelreviewgrade",
            unique_together={("review_score", "grade_id")},
        ),
        migrations.AlterUniqueTogether(
            name="hotelreviewscoredistribution",
            unique_together={("review_score", "tier_id")},
        ),
        migrations.AddIndex(
            model_name="hotelreviewsnippet",
            index=models.Index(
                fields=["property"], name="hotel_revie_propert_dc1c28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotelreviewsnippet",
            index=models.Index(
                fields=["reviewed_at"], name="hotel_revie_reviewe_24742b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotelvideo",
            index=models.Index(
                fields=["property"], name="hotel_video_propert_d481dc_idx"
            ),
        ),
    ]
