# Generated by Django 5.1.15 on 2026-04-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_hotelimage_hotelimageurl_hotellocationhighlight_and_more"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="vendors.vendor",
            ),
        ),
    ]
